name: petmatch
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  firebase_database: ^10.2.5
  firebase_storage: ^11.2.6
  image_picker: ^1.0.2
  uuid: ^3.0.7
  bottom_navy_bar: ^6.0.0
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.2.3
  cloud_firestore: 4.13.1
  path: ^1.8.3
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
