// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALomoaKwChHM8Pkiu5_V1OHXAni1If0j4',
    appId: '1:355338399224:web:5de7ac47b97470dadd7a0d',
    messagingSenderId: '355338399224',
    projectId: 'petmatch-d2dec',
    authDomain: 'petmatch-d2dec.firebaseapp.com',
    databaseURL: 'https://petmatch-d2dec-default-rtdb.firebaseio.com',
    storageBucket: 'petmatch-d2dec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQrTaoDHscohY7I6cnNkdgD_vEk5H3x1o',
    appId: '1:355338399224:android:f092b096ac5e58e5dd7a0d',
    messagingSenderId: '355338399224',
    projectId: 'petmatch-d2dec',
    databaseURL: 'https://petmatch-d2dec-default-rtdb.firebaseio.com',
    storageBucket: 'petmatch-d2dec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_n6b4MRKW4-vyioL2n6G-N6Y3aZaH4PI',
    appId: '1:355338399224:ios:c4525eb8880fbe34dd7a0d',
    messagingSenderId: '355338399224',
    projectId: 'petmatch-d2dec',
    databaseURL: 'https://petmatch-d2dec-default-rtdb.firebaseio.com',
    storageBucket: 'petmatch-d2dec.appspot.com',
    iosBundleId: 'com.example.petmatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_n6b4MRKW4-vyioL2n6G-N6Y3aZaH4PI',
    appId: '1:355338399224:ios:6682f18edd5518f8dd7a0d',
    messagingSenderId: '355338399224',
    projectId: 'petmatch-d2dec',
    databaseURL: 'https://petmatch-d2dec-default-rtdb.firebaseio.com',
    storageBucket: 'petmatch-d2dec.appspot.com',
    iosBundleId: 'com.example.petmatch.RunnerTests',
  );
}
